In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
path = os.path.join('Data','Raw')
nome_file = 'Player Shooting.csv'

df = pd.read_csv( os.path.join( path, nome_file ) )
file_teams = 'Team Abbrev.csv'
teams_abb = pd.read_csv( os.path.join(path, file_teams))
#Visualizzo i nomi delle colonne per facilitare i passi successivi
df.columns

Index(['seas_id', 'season', 'player_id', 'player', 'birth_year', 'pos', 'age',
       'experience', 'lg', 'tm', 'g', 'mp', 'fg_percent', 'avg_dist_fga',
       'percent_fga_from_x2p_range', 'percent_fga_from_x0_3_range',
       'percent_fga_from_x3_10_range', 'percent_fga_from_x10_16_range',
       'percent_fga_from_x16_3p_range', 'percent_fga_from_x3p_range',
       'fg_percent_from_x2p_range', 'fg_percent_from_x0_3_range',
       'fg_percent_from_x3_10_range', 'fg_percent_from_x10_16_range',
       'fg_percent_from_x16_3p_range', 'fg_percent_from_x3p_range',
       'percent_assisted_x2p_fg', 'percent_assisted_x3p_fg',
       'percent_dunks_of_fga', 'num_of_dunks', 'percent_corner_3s_of_3pa',
       'corner_3_point_percent', 'num_heaves_attempted', 'num_heaves_made'],
      dtype='object')

In [3]:
df

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,fg_percent_from_x16_3p_range,fg_percent_from_x3p_range,percent_assisted_x2p_fg,percent_assisted_x3p_fg,percent_dunks_of_fga,num_of_dunks,percent_corner_3s_of_3pa,corner_3_point_percent,num_heaves_attempted,num_heaves_made
0,31136,2024,5025,A.J. Green,NaN,SG,24,2,NBA,MIL,...,0.500,0.408,0.857,0.942,0.000,0,0.225,0.447,0,0
1,31137,2024,5026,A.J. Lawson,NaN,SG,23,2,NBA,DAL,...,0.500,0.260,0.610,1.000,0.107,12,0.640,0.250,0,0
2,31138,2024,5027,AJ Griffin,NaN,SF,20,2,NBA,ATL,...,0.250,0.256,0.750,0.800,0.016,1,0.205,0.250,0,0
3,31139,2024,4219,Aaron Gordon,NaN,PF,28,10,NBA,DEN,...,0.417,0.290,0.642,0.850,0.256,171,0.391,0.352,1,0
4,31140,2024,4582,Aaron Holiday,NaN,PG,27,6,NBA,HOU,...,0.350,0.387,0.255,0.810,0.005,2,0.212,0.478,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16780,15656,1997,2632,Willie Burton,NaN,SF,28,6,NBA,ATL,...,0.556,0.283,0.577,1.000,0.052,4,0.130,0.500,0,0
16781,15657,1997,2278,Xavier McDaniel,NaN,PF,33,11,NBA,NJN,...,0.390,0.200,0.504,0.800,0.017,6,0.160,0.500,1,0
16782,15658,1997,2890,Yinka Dare,NaN,C,24,3,NBA,NJN,...,NaN,NaN,0.579,NaN,0.185,7,NaN,NaN,0,0
16783,15567,1997,2540,Šarūnas Marčiulionis,NaN,SG,32,7,NBA,DEN,...,0.542,0.367,0.556,0.727,0.000,0,0.133,0.500,0,0
16784,15659,1997,2891,Žan Tabak,NaN,C,26,3,NBA,TOR,...,0.333,NaN,0.500,NaN,0.099,7,NaN,NaN,0,0

In [4]:
df = df[df['season']>2003]
df = df.drop(columns=['birth_year', 'pos', 'age',
       'experience', 'lg', 'tm',])

In [5]:
df.fillna(0)

,seas_id,season,player_id,player,g,mp,fg_percent,avg_dist_fga,percent_fga_from_x2p_range,percent_fga_from_x0_3_range,...,fg_percent_from_x16_3p_range,fg_percent_from_x3p_range,percent_assisted_x2p_fg,percent_assisted_x3p_fg,percent_dunks_of_fga,num_of_dunks,percent_corner_3s_of_3pa,corner_3_point_percent,num_heaves_attempted,num_heaves_made
0,31136,2024,5025,A.J. Green,56,614,0.423,24.1,0.138,0.026,...,0.500,0.408,0.857,0.942,0.000,0,0.225,0.447,0,0
1,31137,2024,5026,A.J. Lawson,42,311,0.446,13.7,0.587,0.355,...,0.500,0.260,0.610,1.000,0.107,12,0.640,0.250,0,0
2,31138,2024,5027,AJ Griffin,20,171,0.290,19.5,0.371,0.048,...,0.250,0.256,0.750,0.800,0.016,1,0.205,0.250,0,0
3,31139,2024,4219,Aaron Gordon,73,2297,0.556,7.4,0.807,0.554,...,0.417,0.290,0.642,0.850,0.256,171,0.391,0.352,1,0
4,31140,2024,4582,Aaron Holiday,78,1269,0.446,17.3,0.480,0.122,...,0.350,0.387,0.255,0.810,0.005,2,0.212,0.478,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13136,19314,2004,3100,Zydrunas Ilgauskas,81,2539,0.483,7.0,0.993,0.434,...,0.393,0.286,0.651,0.500,0.062,58,0.000,0.000,0,0
13137,19307,2004,3493,Žarko Čabarkapa,49,570,0.411,10.6,0.838,0.350,...,0.353,0.188,0.693,0.833,0.091,16,0.281,0.111,1,0
13138,19309,2004,3364,Željko Rebrača,24,273,0.442,8.1,1.000,0.234,...,0.750,0.000,0.471,0.000,0.026,2,0.000,0.000,0,0
13139,19310,2004,3364,Željko Rebrača,21,222,0.407,7.5,1.000,0.259,...,1.000,0.000,0.455,0.000,0.037,2,0.000,0.000,0,0
13140,19311,2004,3364,Željko Rebrača,3,51,0.522,9.5,1.000,0.174,...,0.500,0.000,0.500,0.000,0.000,0,0.000,0.000,0,0

In [6]:
df.to_parquet( os.path.join( 'Data', 'Parquet', 'assistedstats.parquet') )